sudo: true

language: perl
perl:
  - "5.24"
  - "5.22"

before_install:
  - cpanm -n Devel::Cover::Report::Coveralls Module::Install Module::Install::AuthorRequires
  - sudo apt-get update
  - sudo apt-get install libpng-dev libjpeg-dev

script:
  PERL5OPT=-MDevel::Cover prove -lv t && cover -report coveralls

notifications:
  irc:
    channels:
      - "irc.freenode.org#chupei.pm"
    use_notice: true
